### ISSUE TITLE
SEGV after "Set as default" in master

### ISSUE THREAD

**Issue by mattgodbolt** [tom-seddon/b2#37]
I was flailing about like a fool trying to work out how to make it a Master128 from thecmd line. I found the Tools->Configurations. I clicked the "Copy" on the master128 by mistake, then clicked "set as default".

I re-ran and got a segv:

```
~/d/b/b/d.linux (master|✔) $ gdb --args ./src/b2/b2 -0 ~/dev/jsbeeb/discs/twister.ssd
GNU gdb (Ubuntu 8.2.91.20190405-0ubuntu3) 8.2.91.20190405-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./src/b2/b2...
(gdb) r
Starting program: /home/matthew/dev/b2/build/d.linux/src/b2/b2 -0 /home/matthew/dev/jsbeeb/discs/twister.ssd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff56b6700 (LWP 14969)]
[New Thread 0x7ffff4eb5700 (LWP 14970)]
[New Thread 0x7fffeec86700 (LWP 14971)]
[New Thread 0x7fffed8ff700 (LWP 14972)]
[New Thread 0x7fffed8be700 (LWP 14974)]
[New Thread 0x7fffed0bd700 (LWP 14975)]
[New Thread 0x7fffec8bc700 (LWP 14976)]
[New Thread 0x7fffb7fff700 (LWP 14977)]
[New Thread 0x7fffb77fe700 (LWP 14978)]
[New Thread 0x7fffb6ffd700 (LWP 14979)]
[New Thread 0x7fffb67fc700 (LWP 14980)]
[New Thread 0x7fffb5ffb700 (LWP 14981)]
[New Thread 0x7fffb57fa700 (LWP 14982)]
[New Thread 0x7fffb4ff9700 (LWP 14983)]
[New Thread 0x7fff97fff700 (LWP 14984)]
[New Thread 0x7fff977fe700 (LWP 14985)]
RTC...: Write $0A; 10; A: value now: 32; $20
RTC...: Write $0B; 11; B: value now: 2; $02

Thread 1 "b2" received signal SIGSEGV, Segmentation fault.
ConfigsUI::DoEditConfigGui (this=0x555556e888d0, config=0x555555edcf70, editable_config=0x555555edcf70) at ../../src/b2/ConfigsUI.cpp:181
181	            if(!editable_config->disc_interface->uses_1MHz_bus) {
(gdb) bt
#0  0x000055555564a3ee in ConfigsUI::DoEditConfigGui(BeebConfig const*, BeebConfig*) (this=0x555556e888d0, config=0x555555edcf70, editable_config=0x555555edcf70) at ../../src/b2/ConfigsUI.cpp:181
#1  0x0000555555649d56 in ConfigsUI::<lambda(const BeebConfig*, BeebConfig*)>::operator()(const BeebConfig *, BeebConfig *) const
    (__closure=0x7fffffffc2b0, config=0x555555edcf70, editable_config=0x555555edcf70) at ../../src/b2/ConfigsUI.cpp:54
#2  0x000055555564ac72 in std::_Function_handler<bool(const BeebConfig*, BeebConfig*), ConfigsUI::DoImGui(CommandContextStack*)::<lambda(const BeebConfig*, BeebConfig*)> >::_M_invoke(const std::_Any_data &, const BeebConfig *&&, BeebConfig *&&) (__functor=..., __args#0=@0x7fffffffc0f0: 0x555555edcf70, __args#1=@0x7fffffffc0e8: 0x555555edcf70) at /usr/include/c++/8/bits/std_function.h:282
#3  0x00005555555b2379 in std::function<bool (BeebConfig const*, BeebConfig*)>::operator()(BeebConfig const*, BeebConfig*) const (this=0x7fffffffc2b0, __args#0=0x555555edcf70, __args#1=0x555555edcf70)
    at /usr/include/c++/8/bits/std_function.h:687
#4  0x00005555555af37e in BeebWindows::<lambda(const BeebConfig*, const iterator&)>::operator()(const BeebConfig *, const std::vector<BeebConfig, std::allocator<BeebConfig> >::iterator &) const
    (__closure=0x7fffffffc250, config=0x555555edcf70, it=
  {name = "Master 128 (MOS 3.20) (2)", beeb_type = 2, os_file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/mos.rom", roms = {{file_name = "", writeable = false}, {file_name = "", writeable = false}, {file_name = "", writeable = false}, {file_name = "", writeable = false}, {file_name = "", writeable = true}, {file_name = "", writeable = true}, {file_name = "", writeable = true}, {file_name = "", writeable = true}, {file_name = "", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/dfs.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/viewsht.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/edit.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/basic4.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/adfs.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/view.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/terminal.rom", writeable = false}}, keyboard_links = 0 '\000', nvram_contents = std::vector of length 0, capacity 0, disc_interface = 0x0, video_nula = true, ext_mem = false}) at ../../src/b2/BeebWindows.cpp:534
#5  0x00005555555b0722 in std::_Function_handler<bool(const BeebConfig*, const __gnu_cxx::__normal_iterator<BeebConfig*, std::vector<BeebConfig, std::allocator<BeebConfig> > >&), BeebWindows::ForEachConfig(const std::function<bool(const BeebConfig*, BeebConfig*)>&)::<lambda(const BeebConfig*, const iterator&)> >::_M_invoke(const std::_Any_data &, const BeebConfig *&&, const __gnu_cxx::__normal_iterator<BeebConfig*, std::vector<BeebConfig, std::allocator<BeebConfig> > > &) (__functor=..., __args#0=@0x7fffffffc1c0: 0x555555edcf70, __args#1=
  {name = "Master 128 (MOS 3.20) (2)", beeb_type = 2, os_file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/mos.rom", roms = {{file_name = "", writeable = false}, {file_name = "", writeable = false}, {file_name = "", writeable = false}, {file_name = "", writeable = false}, {file_name = "", writeable = true}, {file_name = "", writeable = true}, {file_name = "", writeable = true}, {file_name = "", writeable = true}, {file_name = "", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/dfs.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/viewsht.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/edit.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/basic4.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/adfs.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/view.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/terminal.rom", writeable = false}}, keyboard_links = 0 '\000', nvram_contents = std::vector of length 0, capacity 0, disc_interface = 0x0, video_nula = true, ext_mem = false}) at /usr/include/c++/8/bits/std_function.h:282
#6  0x00005555555b163d in std::function<bool (BeebConfig const*, __gnu_cxx::__normal_iterator<BeebConfig*, std::vector<BeebConfig, std::allocator<BeebConfig> > > const&)>::operator()(BeebConfig const*, __gnu_cxx::__normal_iterator<BeebConfig*, std::vector<BeebConfig, std::allocator<BeebConfig> > > const&) const (this=0x7fffffffc250, __args#0=0x555555edcf70, __args#1=
  {name = "Master 128 (MOS 3.20) (2)", beeb_type = 2, os_file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/mos.rom", roms = {{file_name = "", writeable = false}, {file_name = "", writeable = false}, {file_name = "", writeable = false}, {file_name = "", writeable = false}, {file_name = "", writeable = true}, {file_name = "", writeable = true}, {file_name = "", writeable = true}, {file_name = "", writeable = true}, {file_name = "", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/dfs.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/viewsht.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/edit.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/basic4.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/adfs.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/view.rom", writeable = false}, {file_name = "/home/matthew/dev/b2/build/d.linux/src/b2/assets/roms/m128/3.20/terminal.rom", writeable = false}}, keyboard_links = 0 '\000', nvram_contents = std::vector of length 0, capacity 0, disc_interface = 0x0, video_nula = true, ext_mem = false}) at /usr/include/c++/8/bits/std_function.h:687
#7  0x00005555555ad912 in ForEachBeebConfig(const std::function<bool(const BeebConfig*, const __gnu_cxx::__normal_iterator<BeebConfig*, std::vector<BeebConfig, std::allocator<BeebConfig> > >&)> &) (fun=...)
    at ../../src/b2/BeebWindows.cpp:111
#8  0x00005555555af3f4 in BeebWindows::ForEachConfig(std::function<bool (BeebConfig const*, BeebConfig*)> const&) (fun=...) at ../../src/b2/BeebWindows.cpp:531
#9  0x0000555555649d97 in ConfigsUI::DoImGui(CommandContextStack*) (this=0x555556e888d0, cc_stack=0x555555f05d28) at ../../src/b2/ConfigsUI.cpp:53
#10 0x00005555555f8e1d in BeebWindow::DoSettingsUI() (this=0x555555f051b0) at ../../src/b2/BeebWindow.cpp:824
#11 0x00005555555f8a35 in BeebWindow::DoImGui(unsigned long) (this=0x555555f051b0, ticks=254619191352949) at ../../src/b2/BeebWindow.cpp:682
#12 0x00005555555fc12b in BeebWindow::HandleVBlank(unsigned long) (this=0x555555f051b0, ticks=254619191352949) at ../../src/b2/BeebWindow.cpp:1637
#13 0x00005555555fd9f8 in BeebWindow::HandleVBlank(VBlankMonitor*, void*, unsigned long) (this=0x555555f051b0, vblank_monitor=0x555555efeda0, display_data=0x555555f040b0, ticks=254619191352949)
    at ../../src/b2/BeebWindow.cpp:2179
#14 0x00005555555ae4ec in BeebWindows::HandleVBlank(VBlankMonitor*, void*, unsigned long) (vblank_monitor=0x555555efeda0, display_data=0x555555f040b0, ticks=254619191352949) at ../../src/b2/BeebWindows.cpp:320
#15 0x0000555555583c6c in main2(int, char**, std::shared_ptr<MessageList> const&) (argc=3, argv=0x7fffffffdf48, init_message_list=std::shared_ptr<MessageList> (use count 3, weak count 1) = {...})
    at ../../src/b2/b2.cpp:1075
#16 0x00005555555842d7 in main(int, char**) (argc=3, argv=0x7fffffffdf48) at ../../src/b2/b2.cpp:1173
```

**Comment by mattgodbolt** [comment]
I blew away my b2 config dir and retried without the "copy configuration" and all's OK now.

**Comment by tom-seddon** [comment]
Hopefully fixed by https://github.com/tom-seddon/b2/commit/c9e8c7e3612b6c97ad5d0e2a5beb695748bce70a - this option is now gone.
